version: '2.1'

services:
  postgres-db:
    container_name: postgres-db
    build: ./src/db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: OoMUDgwLGG
    ports:
      - 5433:5432
    healthcheck:
      test: exit 0

  api-gateway:
    container_name: api-gateway
    build: .
    volumes:
      - .:/usr/src
      - ./package.json:/usr/src/package.json
    # labels:
    #   - "traefik.backend=api"
    #   - "traefik.frontend.rule=PathPrefix: /api"
    #   - "traefik.port=8789"
    #   - "traefik.frontend.entryPoints=http"
    ports:
      - "3000:3000"
    environment:
      API_PORT: 3000
      API_HOST: 0.0.0.0
      DATABASE_URL: postgres://postgres:OoMUDgwLGG@postgres-db:5432/hotel_dev
      DATABASE_TEST_URL: postgres://postgres:OoMUDgwLGG@postgres-db:5432/hotel_test
      TOKEN_SECRET: DiUhoxLHGP
      NODE_ENV: ${NODE_ENV}
    depends_on:
      postgres-db:
        condition: service_healthy
    links:
      - postgres-db

  # traefik:
  #   image: traefik
  #   command: --web --docker --docker.domain=docker.localhost --logLevel=DEBUG
  #   ports:
  #     - "3000:80"
  #     - "3001:8080"
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #     - /dev/null:/traefik.toml